### ISSUE TITLE
Jason does not (fully) support usage as a library

### ISSUE THREAD

**Issue by gciatto** [jason-lang/jason#91] opened 2021-04-13 14:35 UTC
I'd love to use Jason as a library in my Gradle-based projects.
In particular I don't want to use Eclipse, nor Atom, nor sticking to any particular IDE.
Plus, I'd like to avoid my projects to contain any `.jar` file.

I know that Jason `.jar`s are available via the following Maven repository: http://jacamo.sourceforge.net/maven2/
So a simple solution coult be to setup my Jason project as follows (I use Kotlin as the build script language):
```kotlin
plugins {
    java
}

repositories {
    maven("http://jacamo.sourceforge.net/maven2")
    mavenCentral()
}

sourceSets {
    main {
        resources {
            srcDir("src/main/asl")
        }
    }
}

dependencies {
    implementation("org.jason-lang", "jason", "2.5-SNAPSHOT")
}

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}
```

Now suppose my project's structure is as follows:
```
.
├── build.gradle.kts
├── helloworld.mas2j
└── src
    └── main
        └── asl
            └── hello_agent.asl
```

I now may want to launch the system via a Gradle task, which I may set up as follows in `build.gradle.kts`:
```kotlin
task<JavaExec>("runHelloWorld") {
    group = "run"
    classpath = sourceSets.getByName("main").runtimeClasspath
    main = "jason.runtime.RunJasonProject"
    standardInput = System.`in`
    args(file("$projectDir/helloworld.mas2j").path)
}
```

Given the output of  `./gradlew dependencies`, I expect that dependencies `ant` and `ant-launcher` are in-classpath when launching Jason via the aforementioned task:
```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- org.jason-lang:jason:2.5-SNAPSHOT
     +--- org.apache.ant:ant:1.10.5
     |    \--- org.apache.ant:ant-launcher:1.10.5
     +--- net.sf.ingenias:jade:4.3
     +--- org.jacamo:cartago:2.3 -> 2.5
     \--- org.jacamo:jaca:2.3 -> 2.5
```

However, if I launch the task **without having never configured Jason** via the `jason.util.ConfigGUI`, I get the following message:
```
Ant is not properly configured! Current value is null
Problem defining the command to run the MAS!
``` 
before the program terminates.
This is astonishing, as the `ant`-related `.jar`s are in-classpath.

Now my point is that I **don't want** developers participating to my project to be constrained to _manually_ configure Jason before they can run a _self-configuring_ Gradle script. 
Plus, Jason's configuration is stored into a `user.properties` file hidden within the user's home directory.
This breaks the self-containedness of my Gradle-projects.

I argue that it would be far better if `jason.runtime.RunJasonProject` could detect that `ant` is in-classpath and start the MAS even if no configuration has been previously performed---i.e. if the `user.properties` file is missing.

**Comment by gciatto-unibo** [comment] 2021-04-13 14:39
One may work around this issue by configuring the task as follows:
```kotlin
task<JavaExec>("runHelloWorld") {
    group = "run"
    classpath = sourceSets.getByName("main").runtimeClasspath
    main = "jason.infra.centralised.RunCentralisedMAS"
    standardInput = System.`in`
    args(file("$projectDir/helloworld.mas2j").path)
}
```
i.e. by launching the `RunCentralisedMAS` directly.
However this is a workaround, and can only work with centralised MAS.

**Comment by jomifred** [comment] 2021-04-13 14:53
Hi @gciatto-unibo ,

what you are trying to do should work, otherwise, it is a bug and should be fixed.

We tried to remove the dependency of local configuration files recently.... I am not sure if it is available in Jason 2.5. Do you mind to try Jason 2.6.2? (it is available in the GitHub repository @cleberjamaral has mentioned in the other thread) 

Note also that the dependency groups has changed:

        implementation("org.jason", "jason", "2.6.2")

**Comment by gciatto-unibo** [comment] 2021-04-13 15:02
I confirm: the issue is still there with version `2.6.2`

**Comment by jomifred** [comment] 2021-04-13 15:10
I didn’t realised you are using jason.runtime.RunJasonProject…. 

I repeated the issue here and will see how to fix it.

**Comment by jomifred** [comment] 2021-04-13 15:37
I hope I have fixed it. Could you try with Jason-2.6.3-SNAPSHOT?
(available in the GitHub repo)

**Comment by jomifred** [comment] 2021-04-13 17:00
It makes sense to use RunCentralisedMAS in gradle. 

RunJasonProject is used to create a script to execute the project (and then run it). Ant is used for this script. Once gradle is used in place of Ant, no need to write scripts.

RunCentralisedMas is not a good name for the class, it will be renamed to RunLocalMAS in the future. Since it runs some agentes (from .mas2j) in the a local machine (a JVM indeed). These local agents may belong to a distributed system.

**Closed** 2023-01-30 12:51 UTC
