### ISSUE TITLE
[Bug?] LiteralImpl hash collision

### ISSUE THREAD

**Issue by MikeVezina** [jason-lang/jason#40] opened 2020-05-23 22:18 UTC
Hi all,
Hope all is well and you are staying safe and healthy.

I was making some customizations to the default belief base class and ran into issues that occurred due to LiteralImpl hash collisions. (I'm not sure if this is deliberate or if this is a bug, so feel free to correct me if necessary.)

### Example
To give a quick example to illustrate the issue, the hash values of the literals `~alice(person(female))` and `alice(~person(female))` are the same. I would expect to get different hash values for both of these LiteralImpl objects.

i.e. the following statement returns true, but should return false:
```
ASSyntax.parseLiteral("~alice(person(female))").calcHashCode() == ASSyntax.parseLiteral("alice(~person(female))").calcHashCode();
```

After taking a quick glance at the code, it seems that it is an issue with the negation of the literals. It seems to me that this only occurs when having exactly one LiteralImpl term and flipping the negation signs on both the base literal (i.e. alice(...) ) and the term ( person(...) ). 

Let me know if you have any questions or thoughts about how this could potentially be corrected!

Thanks,
Michael

**Comment by jomifred** [comment] 2020-05-24 02:35
Dear Michael,

thanks for reporting this bug! specially for the careful investigation of the causes. It was fixed in the last commit. 

Best,

Jomi

**Closed by jomifred** 2020-05-24 02:35 UTC

**Comment by MikeVezina** [comment] 2020-05-25 23:33
Hi again Jomi,

Thank you for the quick response and fix! I think this has potentially introduced a new issue with hashing literals:

Literals with the same functor and terms (but swapped indices) will return the same hash, e.g.:
`test("TermOne", "TermTwo")`
and
`test("TermTwo", "TermOne")`

```
Literal one = ASSyntax.createLiteral("test", ASSyntax.createString("TermOne"), ASSyntax.createString("TermTwo"));
Literal swapped = ASSyntax.createLiteral("test", ASSyntax.createString("TermTwo"), ASSyntax.createString("TermOne"));

// one.hashCode() == swapped.hashCode() evaluates to true.
```

I think a solution would be the following:
(in Structure.java)
```
protected int calcHashCode() {
        int result = super.calcHashCode();
        if(getArity() > 0)
            result += terms.hashCode();
        return result;
    }
```

This delegates the hashing to the terms List, which takes into account the index of each individual object, i.e. a literal with the same terms (but swapped) will not return the same hashcode.

Let me know what you think of this solution!

**Comment by jomifred** [comment] 2020-05-25 23:45
Thanks again Michael for identifying the problem! This particular case was fixed.
